### ISSUE TITLE
Why Basically FNF Remix script is so laggy?

### ISSUE THREAD

**Issue by Skeleton19** [MariyaFurmanova/Library#2]
I mean script eats a lot of fps in the game. Why?

**Comment by Skeleton19** [comment]
Also, in the link of the loadstring: https://rawscripts.net/raw/Basically-FNF:-Remix-AutoPlay-Light-11440 no more script. Fix it please.

**Comment by MariyaFurmanova** [comment]
This script is died. It's not my problem!
